---
  - name: Copy file 1.txt to host
    copy:
      src: files/1.txt
      dest: /home/1.txt

  - name: Print message three times using a loop
    debug:
      msg: "This is message {{ item }}"
    loop:
      - "dima"
      - "give me pls"
      - "100"

  - name: Print os_family of host
    debug:
      msg: "OS family of the host is {{ ansible_os_family }}"

  - name: Set variable
    set_fact:
      my_variable: "dima ty for 100"

  - name: Print variable
    debug:
      msg: "{{ my_variable }}"

  - name: Ensure log directory exists
    delegate_to: localhost
    file:
      path: /files
      state: directory

  - name: Save host IP in log.txt on master
    delegate_to: localhost
    shell: echo "{{ ansible_host }}" >> /files/log.txt
  - name: Reboot host
    delegate_to: "{{ inventory_hostname }}"
    reboot:

  - name: Save reboot time in log.txt
    delegate_to: localhost
    shell: "echo 'Host {{ inventory_hostname }} rebooted at $(date -Ins)' >> /files/log.txt"
